// <auto-generated />
using CentralGamesPlatform.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CentralGamesPlatform.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    [Migration("20210116173504_SeedingDb")]
    partial class SeedingDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CentralGamesPlatform.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Casino Game PC"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Casino Game Mobile"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Casino Game Both Device"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Browser Game PC"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Browser Game Mobile"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Browser Game Both Device"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Download Game PC"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Download Game Mobile"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Download Game Both Device"
                        });
                });

            modelBuilder.Entity("CentralGamesPlatform.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GameId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            CategoryId = 1,
                            Description = "The card game poker where you can potentially win money",
                            ImageThumbnailUrl = "~\\images\\gamethumbnails\\poker.jpg",
                            ImageUrl = "~\\images\\gameimages\\pokerLarge.jpg",
                            IsOnSale = true,
                            Name = "Poker",
                            Price = 5.00m
                        },
                        new
                        {
                            GameId = 2,
                            CategoryId = 2,
                            Description = "Spin the wheel for the chance of winning awesome prizes",
                            ImageThumbnailUrl = "~\\images\\gamethumbnails\\placeholder.gif",
                            ImageUrl = "~\\images\\gameimages\\placeholder.jpg",
                            IsOnSale = true,
                            Name = "Spin the wheel",
                            Price = 5.00m
                        },
                        new
                        {
                            GameId = 3,
                            CategoryId = 3,
                            Description = "Scratch card where any prizes you reveal are yours to keep",
                            ImageThumbnailUrl = "~\\images\\gamethumbnails\\placeholder.gif",
                            ImageUrl = "~\\images\\gameimages\\placeholder.jpg",
                            IsOnSale = true,
                            Name = "Scratch card",
                            Price = 5.00m
                        },
                        new
                        {
                            GameId = 4,
                            CategoryId = 4,
                            Description = "Ride a bike through obstacles to get to the end",
                            ImageThumbnailUrl = "~\\images\\gamethumbnails\\placeholder.gif",
                            ImageUrl = "~\\images\\gameimages\\placeholder.jpg",
                            IsOnSale = true,
                            Name = "Happy Wheels",
                            Price = 10.00m
                        },
                        new
                        {
                            GameId = 5,
                            CategoryId = 5,
                            Description = "Stack blocks neatly to increase your score",
                            ImageThumbnailUrl = "~\\images\\gamethumbnails\\placeholder.gif",
                            ImageUrl = "~\\images\\gameimages\\placeholder.jpg",
                            IsOnSale = true,
                            Name = "Tetris",
                            Price = 10.00m
                        },
                        new
                        {
                            GameId = 6,
                            CategoryId = 6,
                            Description = "Play Pool against your friends",
                            ImageThumbnailUrl = "~\\images\\gamethumbnails\\placeholder.gif",
                            ImageUrl = "~\\images\\gameimages\\placeholder.jpg",
                            IsOnSale = true,
                            Name = "8 Ball Pool",
                            Price = 0.00m
                        },
                        new
                        {
                            GameId = 7,
                            CategoryId = 7,
                            Description = "Use weapons to defeat your enemies",
                            ImageThumbnailUrl = "~\\images\\gamethumbnails\\placeholder.gif",
                            ImageUrl = "~\\images\\gameimages\\placeholder.jpg",
                            IsOnSale = true,
                            Name = "Call of duty",
                            Price = 60.00m
                        },
                        new
                        {
                            GameId = 8,
                            CategoryId = 8,
                            Description = "Slice the falling fruit to increase your score",
                            ImageThumbnailUrl = "~\\images\\gamethumbnails\\placeholder.gif",
                            ImageUrl = "~\\images\\gameimages\\placeholder.jpg",
                            IsOnSale = false,
                            Name = "Fruit Ninja",
                            Price = 5.00m
                        },
                        new
                        {
                            GameId = 9,
                            CategoryId = 4,
                            Description = "Defeat all enemies as the imposter to win",
                            ImageThumbnailUrl = "~\\images\\gamethumbnails\\placeholder.gif",
                            ImageUrl = "~\\images\\gameimages\\placeholder.jpg",
                            IsOnSale = true,
                            Name = "Among us",
                            Price = 5.00m
                        });
                });

            modelBuilder.Entity("CentralGamesPlatform.Models.Game", b =>
                {
                    b.HasOne("CentralGamesPlatform.Models.Category", "Category")
                        .WithMany("Games")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
